### ISSUE TITLE
Live Activity Chart doens't populate as it should

### ISSUE THREAD

**Issue by Sjoerd-Bo3** [nightscout/Trio#11]
Problem:
The live activity only shows the values when I entered the app.
The data that was backfilled or in between data the openings of the app was in the widget. 

Without the simulator/NS it works fine (G7 + Dash instead), but I don't understand why it doesn't display the backfilled data aswell. Because the data is in the app so it should also show in the Live activity right?

Smartphone:
- iPhone 15 Pro Max
- Apple Watch Ultra 2

Settings:
- Simulator Pump
- Nightscout CGM Source
- Backfilled Glucose from nightscout
- Live activities branch Merged with Dev_dependencies branch

![image](https://github.com/nightscout/Open-iAPS/assets/2100083/aed00a08-8208-43e9-8757-d37c4b5fa89b)
![image](https://github.com/nightscout/Open-iAPS/assets/2100083/c7244fe5-6261-4876-8144-74418b7b0c01)
![image](https://github.com/nightscout/Open-iAPS/assets/2100083/b56e7d0c-0fab-416c-9216-6d8c2c92f563)
![image](https://github.com/nightscout/Open-iAPS/assets/2100083/4f7ef39d-abc4-4891-856b-9d68e23db8bb)
![image](https://github.com/nightscout/Open-iAPS/assets/2100083/453e882d-2169-4bc9-9774-ed2cc8e7e7fd)
![image](https://github.com/nightscout/Open-iAPS/assets/2100083/7dba5e8a-9fd5-446f-add4-ab86f578e16c)

**Comment by bjornoleh** [comment]
@Sjoerd-Bo3 , is this still an issue, or can it be closed?
