### ISSUE TITLE
Minor iAPS left-overs

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Trio#136]
These are nits - just providing this list so they are available for update when and if desired.

I am testing only alpha branch (soon to be dev).
Configuration: commit 99effeb7

This is a plist file so a little different:
* Open-iAPS/FreeAPS/Resources/Info.plist
* contains `<string>com.artificial-pancreas-iaps</string>`

The rest of these are in *.swift files and indicate the line numbers where hard-coded "iAPS" exists:
* FreeAPS/Sources/Shortcuts/State/
    * ListStateIntent.swift, line 6, 12, (not sure about the `StateiAPSResults`, see next file)
    * StateIntentRequest.swift (I suspect this should be left alone - I do not know what it does)
    * ListStateView.swift (same comment)

Note: many of the rest of these should (later) be modified to use appName instead of hard coded string
   * I did not list all the places with hard-coded Open-iAPS but there are a lot
   * In the short term - simplest solution is to replace the hard-coded "iAPS" with hard-coded "Open-iAPS"
   * Next update, we can modify to using appName instead - that takes more time and effort

Hard-coded string from iAPS to Open-iAPS
* Open-iAPS/FreeAPS/Sources/Application/FreeAPSApp.swift, line 58
* Open-iAPS/FreeAPS/Sources/Modules/HealthKit/View/AppleHealthKitRootView.swift line 16 
* Open-iAPS/FreeAPS/Sources/Modules/NightscoutConfig/View/NightscoutConfigRootView.swift lines 106 and 132
* Open-iAPS/FreeAPS/Sources/Modules/NotificationsConfig/View/NotificationsConfigRootView.swift line 95
* Open-iAPS/FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift lines 44, 240, 381
* Open-iAPS/FreeAPS/Sources/Modules/PreferencesEditor/View/PreferencesEditorRootView.swift line 25
* Open-iAPS/FreeAPS/Sources/Services/WatchManager/GarminManager.swift line 160
* Open-iAPS/FreeAPS/Sources/Services/Calendar/CalendarManager.swift line 96
* Open-iAPS/FreeAPSWatch WatchKit Extension/ComplicationController.swift lines 11, 55

Hard-coded string from FAX to Open-iAPS
* Open-iAPS/FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift line 150
* Open-iAPS/FreeAPSWatch WatchKit Extension/ComplicationController.swift lines 62, 81

**Comment by marionbarker** [comment]
Here are some links for your review:

refers to `widgetURL(URL(string: "freeaps-x://"))`
* https://github.com/nightscout/Trio/blob/dev/LiveActivity/LiveActivity.swift#L291

refers to a loopandlearn dot org page that I don't think exists anymore
* https://github.com/nightscout/Trio/blob/dev/FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift#L35

The same phrase is in all the strings files too.

Other than this, I believe the left-overs are taken care of.

**Comment by bjornoleh** [comment]
> Here are some links for your review:
> 
> refers to `widgetURL(URL(string: "freeaps-x://"))`
> 
> * https://github.com/nightscout/Trio/blob/dev/LiveActivity/LiveActivity.swift#L291

Thanks.

The url string can be updated to the hardcoded "Trio-x://". But we should probably use $(APP_URL_SCHEME) instead. Will have to test before making a PR. If someone wants to pick that up before me, please go ahead.

https://github.com/nightscout/Trio/blob/f23b38ad8b1ca3865ffc56482bf6c6740cad8ecf/Config.xcconfig#L9

https://github.com/nightscout/Trio/blob/f23b38ad8b1ca3865ffc56482bf6c6740cad8ecf/FreeAPS/Resources/Info.plist#L36-L38

**Comment by bjornoleh** [comment]
> 
> refers to a loopandlearn dot org page that I don't think exists anymore
> 
> * https://github.com/nightscout/Trio/blob/dev/FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift#L35
> 
> The same phrase is in all the strings files too.
> 
> Other than this, I believe the left-overs are taken care of.

Perhaps this is something for @t1dude to look at, to get to grips with how we best make changes to strings that are translated, now that Crowdin is being set up.

**Comment by bjornoleh** [comment]
@MikePlante1 , I am nut sure what this does. I assumed it was to open the app when tapping the Live Activity, but that works also when `URL(string: "freeaps-x://"`

https://github.com/nightscout/Trio/blob/f23b38ad8b1ca3865ffc56482bf6c6740cad8ecf/LiveActivity/LiveActivity.swift#L291 

I made the PR #197 anyways, for completeness. (replacing the old `URL(string: "freeaps-x://"`)

**Comment by marionbarker** [comment]
Closing this as completed now that PR #197 is merged.

**Comment by bjornoleh** [comment]
> 
> 
> > 
> 
> > refers to a loopandlearn dot org page that I don't think exists anymore
> 
> > 
> 
> > * https://github.com/nightscout/Trio/blob/dev/FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorStateModel.swift#L35
> 
> > 
> 
> > The same phrase is in all the strings files too.
> 
> > 
> 
> > Other than this, I believe the left-overs are taken care of.
> 
> 
> 
> Perhaps this is something for @t1dude to look at, to get to grips with how we best make changes to strings that are translated, now that Crowdin is being set up.

@marionbarker , the LnL link is not fixed yet, but probably will be when #216 is merged.
