### ISSUE TITLE
Submodule tests are not run automatically, failure in CalibrationsTest

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Trio#146]
**Describe the bug**
1. When running Tests in Xcode, expect submodule tests to run automatically
2. The CalibrationsTests in FreeAPSTest is failing and should be fixed

**To Reproduce**
1. Open Xcode
3. Build to a simulator
4. Run Tests

**Expected behavior**
1. All tests should run (including submodules.
2. All tests should pass

The 4 XCTAssert line that fail are: lines 34, 36, 38 and 42 for `FreeAPSTests/CalibrationsTests.swift`

**Comment by marionbarker** [comment]
I kept meaning to test this but life got in the way.
This was fixed with PR #206 
I confirmed once again that automatic tests are working just fine; they all passed.

**Comment by bjornoleh** [comment]
Marking as completed based on Marion’s test.
