### ISSUE TITLE
Remove the experimental in Temp target view

### ISSUE THREAD

**Issue by avouspierre** [nightscout/Trio#154]
**Is your feature request related to a problem? Please describe.**
The temp target view allows to activate a experimental slider to "simulate" a target in regard of the % basal insulin (HBT) . Now, the implementation is done with Override profil and not useful to stay here
![CleanShot 2024-05-06 at 13 41 56](https://github.com/nightscout/Open-iAPS/assets/4339604/8da14b41-2e14-42a6-9617-c03a5800bc0e)

**Describe the solution you'd like**
remove this part in the view and all code associated in HomeView and others...

**Describe alternatives you've considered**
no object

**Additional context**

**Comment by mountrcg** [comment]
There is not just Loop users migrating to Trio, but also AAPS users who are familiar with TT and exercise mode. This gives them a great usability and flexibility for TempTargets.

**Comment by bjornoleh** [comment]
I don't think it was proposed to remove temp targets as such, only the slider. But there might be a case for keeping it still? Your implementation seems to take target and percent insulin as input, and adjust halfBasal target?

**Comment by avouspierre** [comment]
I don't want to remove TT but remove the slider and the logic behind. I don't understand the difference between the experimental slider and the override function. For me, it is a duplicate function and override allows to do more options. I know @mountrcg that you don't implement override profil but Trio has the functionality.

**Comment by mountrcg** [comment]
Yes I am aware that it is not about removing TTs. But adjusting HBT is what makes TTs flexible as it adjusts the sensitivity change impact for any given TT. So the slider lets you do that quite easily. Its valuable for exercise at different intensities. TT only adjusts sensitivity. Overrides adjust a whole lot of things including CR I think.

**Comment by mountrcg** [comment]
> Your implementation seems to take target and percent insulin as input, and adjust halfBasal target?

yes Jons slider adjusted HBT and the target and calculated the sena ratio. That results in unnatural boundaries for HBT as you need that for the slider.
The slider in autoISF calculates hbt with the input of desired target ans sens ratio. Both have easily defined boundaries.
What is left to do, is that the calc result replaces the current hbt setting in profile, while at the moment it injects the result into oref overriding the hbt that comes from the profile - not good.

**Comment by bjornoleh** [comment]
The CR adjustment is optional in profiles. In addition, SMB can be disabled permanently or on schedule for the duration of the profile/override.

**Comment by avouspierre** [comment]
The difference between temp target with experimental and override is two different algos : 
the first will modify HBT before sending to oref. and determinebasal is based on this new HBT profile. 

the second did not change hbt but send the "override pourcentage" to oref. oref use the override to recalculate the ISF (and eventually the CR). 

So, the result could be different ? Do we have to stay with this 2 algos in Trio ? @MikePlante1  ?

**Comment by mountrcg** [comment]
Yes indeed 2 different things. TT is short term, especially sports or eating soon stuff where only isf is adjusted, nothing else.
At the moment where you adjust cr, isf, basal etc you are on a not-so-short term adjustment reason. This gets mixed up in the current override implementation because people are used to that from Loop.

**Comment by dnzxy** [comment]
I‘d vote for fixing the TT slider rather than removing it. There are different types of users and those that use TTs will want to be able to adjust their HBT, the slider is just not a really good implementation to it.

**Comment by dnzxy** [comment]
> The difference between temp target with experimental and override is two different algos 

It’s not different algorithms, it’s different inputs that result in different outputs. As long as it’s clearly documented and intuitive to the user what the difference in input and output is (currently I‘d say it’s not), that’s an okay thing to have in the app and would work as expected.

**Comment by mountrcg** [comment]
refer to https://github.com/mountrcg/Trio/commit/7974cc252ca0d66070f7403410dd3f2ba92dc11f as a coomit for Trio improving the TT slider.
