### ISSUE TITLE
[Feature request]-“Add pump” button when pump has not been configured 

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/Trio#171]
We now have an “Add CGM” button when no CGM is configured. Perhaps we should have a similar button for to set up a pump when not configured?

![image](https://github.com/nightscout/Trio/assets/63544115/2b21ff94-7b55-4bf3-9fe2-0308fd7ef4e2)

Tagging @avouspierre

**Comment by avouspierre** [comment]
What do you think with this proposal ? @bjornoleh   

![Simulator Screenshot - iPhone 15 - 2024-05-14 at 15 22 45](https://github.com/nightscout/Trio/assets/4339604/27383500-063d-4d52-8526-9fe027e691a4)

**Comment by bjornoleh** [comment]
Looks pretty good. I don't have a better suggestion for a pump pictogram, but perhaps someone else will weigh in?
