### ISSUE TITLE
Guardrails for TT & Profiles

### ISSUE THREAD

**Issue by MRMProd** [nightscout/Trio#185]
**Is your feature request related to a problem? Please describe.**
A safety concern when it is possible to apply a TT or Profile override with bg target below oref (safety) limitation of 4.4 mmol/L. 

**Describe the solution you'd like**
TT & Profile overrides should be limited to 4.4. And in setting > Target glucose > not be able to set below 4.4 Oref will automatically limit set target glucose to 4.4 but not limit TT & Profiles

**Describe alternatives you've considered**
A warning when to apply a TT or profile when below oref safety limit 4.4

**Comment by mountrcg** [comment]
May be we should think about a set of guard rails / input limits in general. Those could be maintained within an extra protected layer with additional warnings and authorization.
