### ISSUE TITLE
ISF value in enacted pop-up "pill" shows only final ISF

### ISSUE THREAD

**Issue by MRMProd** [nightscout/Trio#186]
**Describe the bug**
In the pop-up pill ISF value shows final ISF two times, "**ISF: 2.2 > 2.2**"

**To Reproduce**
1. Enable an Override with adjustment to ISF
2. Click on loop symbol to bring up the pill..'
3. See error

**Expected behavior**
correct should be in my example "**ISF:3.0 > 2.2**"

**Screenshots**
![IMG_54F0D4D19230-1](https://github.com/nightscout/Trio/assets/151788311/32e08913-a8d7-48e4-b6fe-2e592ac87b2c)

* Trio version, branch and git reference (see Trio Settings)
v0.1.0

**Comment by bjornoleh** [comment]
I think this is feature and not bug. The ISF value is adjusted according to the override, but dynamic ISF or autosens is still able to adjust ISF on top of this, which would show up as the ISF value at the right hand side of the arrow. 

I think this issue can be closed as not  being a bug?

**Comment by MRMProd** [comment]
This is strange, can you see a change made by dynamic ISF on the pill? I have set autosens min and max to 1 and still after 3 loops shows auto sense ratio 0.7? When enabling dynamics ISF and using sigmoid and my test phone has bg delta high so dynamics adjustment should be high but no change in the pill? My TRIO version are not latest so will update tonight and do same test again. 
![IMG_7728 2](https://github.com/nightscout/Trio/assets/151788311/195acdb9-c9a3-468e-89a6-75555a7b51e4)
![IMG_7729](https://github.com/nightscout/Trio/assets/151788311/aceebbb6-f544-4ee5-a6d6-09740b2a5ed7)

**Comment by dnzxy** [comment]
@MRMProd could you please provide a more verbose list of steps of what exactly you are doing and what outcome you see but that isn’t along the lines of what you would expect to be true. 

I must admit I am having a bit of trouble to follow what you are trying to see with which settings under which context where - log and or loop status hud 🤔

**Comment by MRMProd** [comment]
If enabling dynamic ISF and/or dynamic CR nothing shows in the pill?
![IMG_7731](https://github.com/nightscout/Trio/assets/151788311/9c4b8b86-bf88-4a99-8ce0-18c56bfa008e)
![IMG_7733](https://github.com/nightscout/Trio/assets/151788311/a5cc82e5-9955-4ffd-9fdf-6a087f065522) the scheduled ISF are 3

**Comment by MRMProd** [comment]
Here are an old 2.3.3 with Dynamic ISF and CR enabled
![415976157_10231599999165778_1142577532351990099_n 2](https://github.com/nightscout/Trio/assets/151788311/8cb5aa24-828c-492b-b94a-6cd7dfcad37f)

**Comment by dnzxy** [comment]
Have there been >1 loop cycles between you enabling it and looking at the hud? Sorry for asking seemingly weird question, just trying to get all details of what you do and what the expected outcome is.

**Comment by MikePlante1** [comment]
@MRMProd Your 2.3.3 screenshot shows that DynamicISF is being used with Sigmoid off (all the purple blocks) and that Autosens has been calculated by DynamicISF to be 0.7.

Your Trio screenshot however, does not show DynamicISF being used at all, and Autosens is set to 1, therefore both `X` and `Y` in `X->Y` are the same.

Like @dnzxy mentioned, the HUD only changes after a loop cycle is ran, so toggling on Dynamic ISF (and CR) won't affect the HUD until the next loop cycle runs.

But also, has Trio been running for 21+ hours with a real pump and cgm attached to it? Because DynamicISF requires a minimum of 21 hours of insulin data to run.

**Comment by MikePlante1** [comment]
> Little confused with "EnableDynamicISF" called "useNewFormula" now

I agree that name is dumb, but that's what it was called in 2.3.3, and looks like it's still called that in the latest iAPS 4.2.0

**Comment by MRMProd** [comment]
Everything seems to work now, you can close this "bug". Most of the issue was 21+ hours making the display not showing correctly. One thing I can add to enhancement is changing the name in the pill from Autosense Ratio xx to Dynamic Ratio when dynamic is used. This is confusing for new users when they think it is auto sense but in reality is dynamic ratio (when dynamic is used). I did get Jon to change that in the new version just to clarify for new users. Sorry for taking up time from you guys but is was really strange before 21 hrs + used.
