### ISSUE TITLE
Update PopUp descriptions

### ISSUE THREAD

**Issue by tmhastings** [nightscout/Trio#195]
**Is your feature request related to a problem? Please describe.**

Pop-ups are difficult for general users to understand, and formatting is inconsistent

**Describe the solution you'd like**

Implement a consistent format for the pop-up information so each contains:
- a description of the setting
- the default value

This should be combined with a restructuring of the menus for better UX that leads to users having a better understanding of when each setting is utilized by Trio. The restructuring work is already in progress by @polscm32 and @dnzxy (PR not yet submitted)

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!
