### ISSUE TITLE
Random Trio crash

### ISSUE THREAD

**Issue by itsmojo** [nightscout/Trio#196]
When I opened up the Trio app, the main screen displayed briefly and when disappeared as the app crashed.

**To Reproduce**
Not reproducible. Only happened that one time...

**Expected behavior**
The app should never crash.

**Screenshots**
NA

**Smartphone**
iPhone 15 Pro Max 512 GB
Running iOS 17.4.1

**Setup Information**
Omnipod DASH
Dexcom G6 and Dexcom G6 app
Trio v0.1.1 (1)
Branch: dev b851a5e
App Expires: May 10, 2025

**Additional context**
Here is the resulting FreeAPS-2024-05-14-133045.ips crash file (renamed as a .txt file) that was created under iPhone Settings->Privacy & Security->Analytics & Improvements->Analytics Data when the app crashed. The app died with a SIGSEGV fault due to a KERN_INVALID_ADDRESS. Additional nearby potentially relevant info included "mach_vm_allocate_kernel failed within call to vm_map_enter". Perhaps Treo's memory allocator got into some bad state?

[FreeAPS-2024-05-14-133045.txt](https://github.com/nightscout/Trio/files/15325145/FreeAPS-2024-05-14-133045.txt)

**Comment by JeremyStorring** [comment]
Investigating

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!
