### ISSUE TITLE
Add Referral Text for Upload Glucose Icon in Nightscout Config

### ISSUE THREAD

**Issue by Sjoerd-Bo3** [nightscout/Trio#199]
### Is your feature request related to a problem? Please describe.
Users are often confused by the grey "upload glucose" icon in Nightscout config, not knowing where to go to enable glucose uploading. This confusion could be avoided with better guidance. Currently, there's no indication in the Nightscout config on how to enable this feature, leading to potential frustration and delays in data uploading.

### Describe the solution you'd like
Add a referral text next to the grey "upload glucose" icon in the Nightscout config. The text should guide users on where to go to enable glucose uploading, such as "Please go to [specific location] to enable uploading glucose." This would improve user experience by providing clear instructions.

### Describe alternatives you've considered
- Adding a button that directly opens the CGM module instead of just referral text. *(Submodules changes needed)*
- Implementing a notification system to alert users on transmitter change that they need to re-enable glucose uploading. *(Would need a separate Issue?)*
- Exploring the possibility of defaulting the glucose upload setting to "on" for new users or after transmitter swaps. *(Submodules changes needed and discussed at other places to not do this)*

### Additional context
The need for this improvement was discussed extensively, with several users noting the inconvenience caused by the current setup. Mike Plante mentioned the repetitive need to toggle the setting after every transmitter swap, which is particularly annoying for G6 users. Dan and Sjoerd noted that while the setting is connected, it’s not changeable from the Nightscout settings. Implementing this small change would significantly enhance the user experience and reduce confusion.

![image](https://github.com/nightscout/Trio/assets/2100083/2a876e12-8854-46a4-915d-083e2cc941c6)

---

**Note:** This request aims to enhance the usability of the Nightscout config by providing clear guidance on enabling glucose uploads, ultimately making the system more user-friendly and reducing the likelihood of user errors.

**Comment by Sjoerd-Bo3** [comment]
Comment from Daniel:
Hi again,

I added an "allow NS download toggle" to my personal iAPS build a couple of weeks ago. Just made a commit to a fresh Trio dev testing branch with the same changes. Feel free to use and improve this as you like (Super simple code implementation, but it works)
https://github.com/dsnallfot/Trio/commit/b8d9a3160a31a417561c602e9e38915777853f35

**Comment by MikePlante1** [comment]
> Add a referral text next to the grey "upload glucose" icon in the Nightscout config. The text should guide users on where to go to enable glucose uploading, such as "Please go to [specific location] to enable uploading glucose." This would improve user experience by providing clear instructions.

Here's a proposed solution for this: https://github.com/nightscout/Trio/pull/338
