### ISSUE TITLE
Feature Request: Indicate on Main screen if no Pod is attached

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Trio#207]
## Is your feature request related to a problem? Please describe.

If a pod is not attached, my screen indicates Pod reservoir value of 50+ U with no time indicated

## Describe the solution you'd like

If a pod is not attached, indicate on the Main Screen that there is no pod

## Describe alternatives you've considered

None - this need to be resolved

### Current Main screen displays

* Add a DASH rPi simulator pod (graphic on left)
   * top portion of pump section shows reservoir level
   * bottom portion of pump section shows time pod is active 
* Deactivate pod (graphic on right)
   * The HUD should indicate No Pod and it does not
   * top portion of pump section is blank
   * bottom portion of pump section shows default reservoir level, even though no pod is attached
   * Note the Nightscout is also given the default pod reservoir level even though no pod is attached - this can be an issue for parents
* wait - eventually get Red Loop and notification that Trio is not looping but only change on main screen is red loop

![trio-issue-no-pod](https://github.com/nightscout/Trio/assets/19607791/b3ab2dff-6e83-453c-8c49-a174b19b533e)

**Comment by bjornoleh** [comment]
@marionbarker , did merging of #218 solve this issue? It be looks like it did, but I could be missing something.

**Comment by marionbarker** [comment]
This is resolved in main and dev.
