### ISSUE TITLE
Unable to dismiss keyboard when clicking note for meal entries

### ISSUE THREAD

**Issue by JeremyStorring** [nightscout/Trio#211]
**Describe the bug**
When you click the meal entry button and click the "Note" section, you are unable to dismiss the keyboard without selecting somewhere else or entering a note.

**To Reproduce**
1. Go to meal entries
2. Click on Note
3. See that you are unable to dismiss the keyboard

**Expected behavior**
If a user misclicks the "Note" section the user should be able to dismiss the keyboard without having to enter a note or clicking somewhere else.

**Screenshots**
![image](https://github.com/nightscout/Trio/assets/37644909/41f6be28-3160-485f-8d9a-2c4f81f5e22b)

**Smartphone (please complete the following information):**
iPhone 14

**Setup Information (please complete the following information):**
* Pump type: Omnipod Dash
* CGM type and CGM app: Dexcom G7 + G7 App
* Trio version, branch and git reference (see Trio Settings): Dev 0.1.0

**Comment by marionbarker** [comment]
I'm a little confused. 
* The dismiss keyboard icon shows up after typing something.
* But tapping Note and then return with no entry, the keyboard goes away.
* Did this enter an empty note into the record? Is that what the bug was?
