### ISSUE TITLE
Important settings should have warnings in app

### ISSUE THREAD

**Issue by JeremyStorring** [nightscout/Trio#212]
**Describe the bug**
Currently, there are settings in the app that are fairly important but do not have in-app information or warnings. An example of this is with DIA, which shouldn't generally be modified and should not be modified to less than 5 hours, but the only warning of such is in the docs themselves.

**Expected behavior**
Any setting that is important but does not have an in-app dialog or warning, should have one so it is easily accessible to the user.

**Smartphone (please complete the following information):**
iPhone 14

**Setup Information (please complete the following information):**
* Pump type: Omnipod Dash
* CGM type and CGM app: Dexcom G7 + G7 App
* Trio version, branch and git reference (see Trio Settings): Dev 0.1.0 

**Additional context**
I'll do a full audit of the settings missing warnings and will add them here.

- DIA - "Duration of insulin action (DIA) affects Trio calculations through its impact on insulin on board (IOB). The default DIA of 5 hours is likely too low and can cause insulin stacking. Increasing to 7 hours should suit most users."
- Closed Loop - Closed Loop is disabled by default. This means Trio cannot make adjustments autonomously. The system relies on your approval of its actions.

**Comment by LiroyvH** [comment]
What's the rationale/supporting evidence behind the 7 hours and based on which insulin?

**Comment by marionbarker** [comment]
I think this comment goes with this topic.

In Trio Preferences, scroll down to the `OPENAPS OTHER SETTINGS` section:
* The default value for `Autotune ISF Adjustment Fraction` is 1
* Tap on the row to see the recommended value is 0.5 (graphic below)

![trio-issue-212](https://github.com/nightscout/Trio/assets/19607791/1d5a8e6d-d89b-43eb-a1c8-be13751f3dfe)

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!
