### ISSUE TITLE
Meal settings has incorrect text

### ISSUE THREAD

**Issue by JeremyStorring** [nightscout/Trio#213]
**Describe the bug**
When you navigate to meal settings, the settable option refers to "Override with a factor of", while the help text below refers to "Adjustment factor". This is not entirely clear, and the settable option should be changed to "Adjustment Factor"

**To Reproduce**
1. Go to Meal Settings
2. Look at text for last option and help text

**Expected behavior**
Set "Override..." with "Adjustment Factor" to match help text.

**Screenshots**
![image](https://github.com/nightscout/Trio/assets/37644909/dd0e9bb4-8c09-41cc-a791-5d60fa4e980f)

**Smartphone (please complete the following information):**
iPhone 14

**Setup Information (please complete the following information):**
* Pump type: Omnipod Dash
* CGM type and CGM app: Dexcom G7 + G7 App
* Trio version, branch and git reference (see Trio Settings): Dev 0.1.0

**Comment by bjornoleh** [comment]
This setting is a scaling factor for the FPU result, to enable adjustments of the Warsaw formula output. I think the name “Adjustment factor” is already ”taken” by the one used by dynamic ISF, so perhaps find a better name for this one. Maybe “FPU Factor”?

**Comment by JeremyStorring** [comment]
That seems reasonable to me, using "FPU Factor" and being consistent should solve the problem!

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!
