### ISSUE TITLE
Resolve text issues in Trio

### ISSUE THREAD

**Issue by JeremyStorring** [nightscout/Trio#217]
Throughout Trio there are references to OpenAPS and Trio in places where this may not be necessary, or could be confusing to a user.

We will need to audit all instances of this in the app (headers, help dialogs, etc), and remove them. This work will also include making some text make more sense.

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!
