### ISSUE TITLE
A Trio history enact page

### ISSUE THREAD

**Issue by MRMProd** [nightscout/Trio#222]
**Is your feature request related to a problem? Please describe.**
When tuning and adjusting it is very helpful with a "Enact history page" where you can see every loop and how the calculations where made.

**Describe the solution you'd like**
A History page like autoISF that is searchable in time and date. Some parameters should be changed to fit Trio better.Long press at "statistics icon" to bring the page up

**Additional context**
See screenshot from autoISF
![IMG_0432](https://github.com/nightscout/Trio/assets/151788311/315efb50-3333-4de1-a380-3a06bb9cea43)

**Comment by Sjoerd-Bo3** [comment]
I could see this be useful when tuning the algorithm. Good idea.

**Comment by MRMProd** [comment]
As a tuning aid, I would like to se an easy assessable slider for ISF. This should be logged in the History table above. Then you can increase/decrease when needed or makes it easier to tune. If I want to test 10% less at a certain time I just slide it to 90%. Idea are from tuning engines but would was ease a lot. A toggle in settings to enable this amazing feature so children wouldn’t change it

**Comment by bjornoleh** [comment]
> As a tuning aid, I would like to se an easy assessable slider for ISF. This should be logged in the History table above. Then you can increase/decrease when needed or makes it easier to tune. If I want to test 10% less at a certain time I just slide it to 90%. Idea are from tuning engines but would was ease a lot. A toggle in settings to enable this amazing feature so children wouldn’t change it

I like the idea. I’d suggest the same for CR and basal. I typically calculate manually what the settings should be if changing by 10 or 15 % relative change. Having this tool in the app would help. A slider is optional, just a field to enter a value for the relative amount of change (+ 10 % etc) would also work (not sure which is less error prone). As long as it’s very clear if the adjustment is relative (10%) or absolute (110%) (if that’s the correct terminology)

**Comment by Sjoerd-Bo3** [comment]
> As a tuning aid, I would like to se an easy assessable slider for ISF. This should be logged in the History table above. Then you can increase/decrease when needed or makes it easier to tune. If I want to test 10% less at a certain time I just slide it to 90%. Idea are from tuning engines but would was ease a lot. A toggle in settings to enable this amazing feature so children wouldn’t change it

@MRMProd Just update the Issue as ideas comeup, so we'll have a complete one when we come to it. Keep it up!

**Comment by Sjoerd-Bo3** [comment]
hey 👋 - silence for 30 days 🤐 ... anybody? triage is required!
