### ISSUE TITLE
Live Activity: does not support 'nightmode' on standby mode

### ISSUE THREAD

**Issue by Sjoerd-Bo3** [nightscout/Trio#228]
**Is your feature request related to a problem? Please describe.**
*The Trio app currently does not support the red night mode, which causes discomfort for users who use the app in low-light environments. The app remains in light mode, causing strain on the eyes, particularly during nighttime usage.*

**Describe the solution you'd like**
*Implement a night mode for the Trio app that reduces screen brightness and uses a red hue to ease eye strain during night-time use. This can be achieved by utilizing the `isLuminanceReduced` attribute in SwiftUI to conditionally set the app's coloring when night mode is enabled.*

**Describe alternatives you've considered**
*1. Allowing users to manually switch between light and dark modes within the app settings.*
*2. Synchronizing the app's theme with the iOS system-wide dark mode settings.*

**Additional context**
*Night mode would significantly enhance the user experience by making the app more comfortable to use in dark environments. The implementation would involve detecting when the iOS system is in night mode or using the `Standby` mode settings to adjust the app's display accordingly.*

**Technical Details**
https://developer.apple.com/documentation/SwiftUI/EnvironmentValues/isLuminanceReduced.*

**User Impact**
*This feature would benefit users who frequently use the Trio live activity at the night stand, reducing eye strain and improving overall comfort. It ensures that the app integrates seamlessly with iOS's night mode settings, providing a consistent user experience.*

**Priority Level**
*Low – While this feature is not critical, it greatly enhances user comfort and usability, especially for those who use the app in low-light conditions.*

---

This feature request details the need for a night mode in the Trio app, leveraging iOS settings to improve user experience in low-light environments.

**Comment by dnzxy** [comment]
The author of the original LiveActivities feature for iAPS @10nas might have a swing at this as indicated on Discord 😊

**Comment by 10nas** [comment]
If I understand correctly you are looking to have the live activity text have a red color when it is shown in standby mode with standby "night mode" enabled.

AFAIK `isLuminanceReduced` signals when an always on display is used and the display is in the "off" state. It does not relate to the standby night mode. I even tested this.

Detecting that the live activity is shown in standby at all via the `isActivityFullscreen` environment variable, whether in standby night mode or not, also doesn't seem to work. This is a dead end too. I tested this.

There seems to be no way to detect standby night mode automatically. As such, there is no real solution to this problem as of now.

As an aside: Even detecting dark mode (the system wide dark mode, not related to standby) in live activities is broken, so Apple has a long way to go. See https://github.com/nightscout/Trio/blob/3be872c7bda4d03a3f0c30b086d2682f680002cb/LiveActivity/LiveActivity.swift#L215 and https://developer.apple.com/forums/thread/734946
