### ISSUE TITLE
Text Box Not Clearing When Adding Multiple Profiles

### ISSUE THREAD

**Issue by kylmcw** [nightscout/Trio#229]
**Describe the bug**
When adding more than 1 profile in the same session i.e. do not let the pop up disappear, the text box for each following profile entry contains the name of the previous profile.

**To Reproduce**
1. Click on profiles
2. enter random configuration
3. Name profile
4. Save
5. Immediately create a new profile with the steps above without exiting the profile view.
6. Notice the name of the previous profile in the text box pre-entered.

**Expected behavior**
Each visit to create a new profile has an empty text box.

**Screenshots**

**Smartphone (please complete the following information):**

**Setup Information (please complete the following information):**
* Pump type - DASH
* CGM type and CGM app - Libre 2
* Trio version, branch and git reference (see Trio Settings) Trio dev f6afb8c

**Additional context**

**Comment by MikePlante1** [comment]
Thanks for reporting this. Solution seems to be pretty simple. Proposed in #230
