### ISSUE TITLE
Trio watch app complication not showing.

### ISSUE THREAD

**Issue by JohnKitching** [nightscout/Trio#257]
Trio (TAI to be fair) watch app installed and working. When trying to add a complication to act as a shortcut to the app it doesn't appear. 

iPhone 15 Pro Max
17.5.1

Apple Watch Ultra
watchOS 
10.5

Modular Ultra Watch face. Trying to add to bottom left complication slot.

**Comment by dsut4392** [comment]
Trio complication w
![incoming-5910B63D-6E94-4EED-8A33-74E35E4464FB](https://github.com/nightscout/Trio/assets/55490253/03694550-17a6-48e2-a254-fd474a37b318)
orks for me in same complication slot on modular watch face on 44mm series 5 (watchOS 10.5).

**Comment by JohnKitching** [comment]
It does for me now! 
I swear it didn't 😂
Took at least an hour after installation for the complication to become available. 
I'll close this issue thank you.

**Comment by bjornoleh** [comment]
For future reference, it’s not unusual having some issue with getting the watch app to install. Most likely this is a watch issue. Rebooting the watch, or just trying again later is often enough.
