### ISSUE TITLE
[Bug] SAGE not updating in NightScout

### ISSUE THREAD

**Issue by TymHuckin** [nightscout/Trio#269]
![image](https://github.com/nightscout/Trio/assets/92105120/75f20aa3-a914-4221-8d2c-e6030ac178b9)

I've noticed that the sensor is doesn't always update in Nightscout. I change the sensor yesterday (G6/Anubis) and it's still showing as over 13 days old. Had this before but then suddenly it updated.
0.1.0  56a3f87 updated on my phone 4 June 2024.

**Comment by aug0211** [comment]
Noticed this with G7 as well.

Let’s all observe closely and gather data on our next sensor changes to provide details and logs so we can help get to the bottom of this.

**Comment by aug0211** [comment]
Observed again today.

1. Existing G7 had issues and stopped getting readings
2. Inserted a new sensor for a “background warmup” while hoping the old sensor would come back online
3. At 25m into “background warmup”, old sensor had still not come online - decided to cut over to new sensor
4. Used the “replace sensor” option in G7 app
5. Scanned QR code in G7 app to pair new sensor
6. Confirmed in G7 app that sensor was already applied
7. “Forgot” old sensor in iOS Bluetooth settings
8. G7 app picked up new sensor
9. Trio began receiving new readings
10. Observed that SAGE in Nightscout was not updated 
11. Observed that no “CGM Sensor Start” (or similar) event had been created in Nightscout by Trio
12. Manually (via Shortcut) added “CGM Sensor Start” event to Nightscout via iOS shortcut
13. Observed SAGE updating in Nightscout after manually running the shortcut

**Comment by bjornoleh** [comment]
The sensor details are stored in a file on your phone, probably in the `Trio/monitor`directory. Could you please look that up and post it here?

**Comment by aug0211** [comment]
Definitely, will do when kiddo is home and I can look at his phone - most likely this evening.

**Comment by bjornoleh** [comment]
For some background, SAGE uploads to Nightscout was implemented by merging this branch:

https://github.com/trixing/freeaps/commits/patch/sage/

After some refactoring, SAGE was later fixed for G6 by this PR:

https://github.com/Artificial-Pancreas/iAPS/pull/212

Then apparently SAGE was broken by a refactor after the transition to submodules in Trio, where relevant files were removed:

https://github.com/nightscout/Trio/commit/47fa01786a7457b30e2307a11e02908719fa0aa9

Later, SAGE was fixed for Libre, but not Dexcom: https://github.com/nightscout/Trio/commit/15713b0f1d5d97cec8273df9edfa02315225a2b0

I assume we would need a similar fix for G6 and G7 SAGE to be updated in NS.

**Comment by aug0211** [comment]
![image](https://github.com/nightscout/Trio/assets/659845/c444d745-d72c-4467-ad12-0eac62c4dde1)

**Comment by bjornoleh** [comment]
@aug0211 , only G6 sessions are written to this file, xdrip sessions are not.

If you look at my sleuthing above, you can track down the deleted files that broke this:

FreeAPS/Sources/APS/CGM/DexcomSourceG5.swift
FreeAPS/Sources/APS/CGM/DexcomSourceG6.swift
FreeAPS/Sources/APS/CGM/PluginSource.swift

Some change likely broke this for G7 at the same time, I have not pinpointed that.
 
The fix for Libre can probably be used as a model to fix this for Dexcom again.

**Comment by bjornoleh** [comment]
I meant exclusively Dexcom sessions (probably including G7), and not xdrip :-)

**Comment by LiroyvH** [comment]
Can confirm, using G6 btw, that the 'cgm-state.json' file has not been updated for me for the new sensor. Last sensor showing up is from 04-05-2024. I changed it on May 31st.

**Comment by snickerdoodleparent** [comment]
+1 here -- for G7. An install of Trio on a new phone June 12, no cgm-state.json file was created. I've tried scanning for new sensor, deleted CGM and added it again, SAGE does not update and cgm-state.json doesn't exist.
