### ISSUE TITLE
“Clear” button for bolus and carb entries does not work as expected 

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/Trio#273]
## Describe the bug

Observation:

Enter a value in the Enact Bolus: Bolus - Amount field
Tap `Clear` and see the entry being cleared out
Tap `Done`to escape the keypad (there is no other way, except swiping down)
Watch how the previous bolus entry reappears.

The same observation has been made for carb entries. 

Some recent PR introduced a button to close the keypad, not sure if any of that could be used here.

## Expected behavior
Clear should mean clear 

### Trio Version:
* Repo: *nightscout/trio*
* current dev 14c7643275e3f351448d7623432f0d1778b65af4

**Comment by marionbarker** [comment]
This was fixed with the merged of #337
