### ISSUE TITLE
Screen did not update when pressing Resume Insulin Delivery following suspend

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Trio#278]
## Describe the bug
During the case where Issue #244 occurred, the user reported that the Resume Insulin Delivery key didn’t appear to be working and so she pressed it multiple times.

## Attach a Log
Please see Issue #244 for detailed analysis

## To Reproduce
We could not reproduce this issue using either the rPi DASH simulator or with an actual Eros pod.

This appears similar to the intermittent UI freezing issue described in #175.

## Expected behavior
The UI should not continue to accept button presses if the display has frozen.

## Screenshots
N/A

## Setup Information (please complete the following information):
Refer to Issue #244

## Technical Details
N/A

## Additional context
N/A

**Comment by dnzxy** [comment]
If the display / app has frozen, it has frozen. Not sure what the expected behaviour for a frozen app would be other then to be… frozen?

**Comment by dnzxy** [comment]
Very likely fixed with the linked PRs, as well as TCD / Trio 1.0.0-dev. 
Please re-open, if still remains.
