### ISSUE TITLE
Pump Settings screen returns to prior value but doesn't say it cannot save

### ISSUE THREAD

**Issue by Sjoerd-Bo3** [nightscout/Trio#286]
Trio is silent with a real Medtronic pump. By silent, I mean the Pump Settings screen returns to prior value but doesn't say it cannot save.

Loop doesn't report an error for too large a value because the guardrails will not allow you to send anything greater than what is allowed (by Loop). For my MDT 515, the max is 25 U (same as the guardrails). 
* If the rileylink is powered off, the modal alert that RL can't be found is prompt.
* If the pump is out of range of the RL, takes longer but an Unable to Save alert is displayed.

![loop-error-unable-to-save](https://github.com/nightscout/Trio/assets/19607791/5193f470-1785-40a3-ad5c-0f3991bce696)

_Originally posted by @marionbarker in https://github.com/nightscout/Trio/issues/266#issuecomment-2146194540_

**Comment by LiroyvH** [comment]
This is connected to #247

**Comment by dnzxy** [comment]
Addressed in TCD / Trio 1.0.0-dev
