### ISSUE TITLE
reduce amount of crown rotation to enact bolus using Apple Watch

### ISSUE THREAD

**Issue by holmfirth** [nightscout/Trio#317]
The amount of rotation required to enact a bolus seems excessive - the 'other' iAPS had an option to reduce the rotation required. Could this be implemented?

**Comment by dnzxy** [comment]
Hi @holmfirth. Thanks for the feature request. This has already been implemented by @MikePlante1 via #275 and will be part of Trio `1.0.0`.

**Comment by MikePlante1** [comment]
It’s actually in dev now, so no need for alpha. Just go to ⚙️> `watch` > `confirm bolus faster`
