### ISSUE TITLE
Cannot set a BG target of 6.1, silent reset to 4 mmol/l

### ISSUE THREAD

**Issue by widmann** [nightscout/Trio#318]
Trio is also affected by this bug:
https://github.com/Artificial-Pancreas/iAPS/issues/712

If I try to set a BG target of 6.1 mmol/l in the UI, the setting is silently reset to 4 mmol/l after saving and exiting the UI. Setting 6.0 or 6.2 mmol/l works, so there is a workaround. However, since there is no visual feedback of the reset and a target of 4 mmol/l could have serious side effects, I would consider this a high priority issue.

Steps to reproduce:

- Open the target BG UI.
- Set a target of 6.1 mmol/l.
- Press save.
- Go back to Settings.
- Re-enter the target BG UI and find the target set to 4 mmol/l.

Expected result:

- BG target set to 6.1 mmol/l.

Actual result:

- BG target set to 4 mmol/l.

A prerequisite is probably setting the BG units to mmol/l, but I have not systematically tested this yet.

**Comment by marionbarker** [comment]
### Summary
I confirm this issue exists with the most recent configuration for Trio-alpha.

### Testing
* updated the latest alpha branch, commit 82f2d01a
* built on existing Trio, SE running iOS 17.5.1
* set units to mmol/L
   * target was  99 mg/dL, now 5.5 mmol/L
   * modify target, save, go to settings, return to target screen:
      * choose 6.0; final 6.0 
      * choose 6.1; final 4.0 
      * choose 6.2; final 6.2

**Comment by Sjoerd-Bo3** [comment]
Did the same testing as Marion with the same outcome.

**Comment by bjornoleh** [comment]
Can confirm this was the same with an older iAPS build (v2.2.5)

**Comment by dsut4392** [comment]
Yep, confirmed same in dev32b5e95 with pump simulator.
