### ISSUE TITLE
Live Activity LastUpdated Time Does Not Reset Changing Timezone

### ISSUE THREAD

**Issue by kylmcw** [nightscout/Trio#325]
## Describe the bug
*A clear and concise description of what the bug is. Describe what you see versus what you expect to see.*
LiveActivity LastUpdated time should reflect the current time of the iPhone.

## Attach a Log
*Tap the Trio settings icon at the bottom of the screen, then tap 'Share logs' on the bottom of the list and attach it to this ticket.*

## To Reproduce
*Steps to reproduce the behavior:*
1. Simulate changing timezone
2. Observe Live Activity Last Updated does not reflect current iPhone time.

## Expected behavior
*A clear and concise description of what you expected to happen.*
Live Acitivty Last Updated should reflect current time.

## Screenshots
*If applicable, add screenshots to help explain your problem.*
![image](https://github.com/nightscout/Trio/assets/156543991/2d2a837a-982f-49ce-a5aa-4510152a3c01)
*iPhone time was 16:03*

### Smartphone:
* Hardware: *[iPhone 15 Pro]*
* OS Version: *[ iOS 17.5.1]*

### Pump:
* Manufacturer: *[Insulet]*
* Model: *[Omnipod Dash]*

### CGM:
* Device: *Libre2*
* Manager app: *Trio*

### Trio Version:
* Version Number: *0.1.0*
* Repo: *kylmcw/trio*
* Git Reference: *8de9979*

## Technical Details
*If applicable, provide any technical details that might help in diagnosing the problem. This could include logs, error messages, or relevant configuration details.*

## Additional context
*Add any other context about the problem here.*
Not sure if it requires additional timezone changes, i didn't notice it when I travelled abroad. maybe it happened both times.

**Comment by dnzxy** [comment]
It will reflect the current timezone of the phone upon next update of the live activity.
Should be the case in Trio 0.2.0 as well as TCD / Trio 1.0.0-dev.
