### ISSUE TITLE
Unable to log glucose entry > 14mmol/L

### ISSUE THREAD

**Issue by dsut4392** [nightscout/Trio#339]
## Describe the bug
When logging finger stick glucose entries with the app set to use mmol/L as units, values greater than 14mmol/L cannot be saved. 

## Attach a Log
*Tap the Trio settings icon at the bottom of the screen, then tap 'Share logs' on the bottom of the list 

## To Reproduce
*Steps to reproduce the behavior:*
1. Set units preference to mmol/L
2. *Click on on centre of chart, then Glucose tab
3. Click on “Log Glucose +”
4. Enter any value greater than “14” and the “Save” button is greyed out, the entry cannot be saved 

## Expected behavior
* values greater than 14mmol/L should be able to be saved. 

## Screenshots
*If applicable, add screenshots to help explain your problem.*
![Uploading image.png…]()

## Setup Information (please complete the following information):

Dev aa26049

### Smartphone:
* Hardware: iPhone 15 Pro Max
* OS Version: iOS 17.5.1

### Pump:

* Model:  Omnipod Dash

### CGM:
* Device: Dexcom G6
* Manager app: Dexcom App

### Trio Version:
* Version Number: Dev 0.1.0
* Repo: *nightscout/trio*
* Git Reference: aa26049

## Technical Details
*If applicable, provide any technical details that might help in diagnosing the problem. This could include logs, error messages, or relevant configuration details.*

## Additional context
*switching app to mg/dL allows entry of BG values up to 720. Should this limit be lowered to reduce safety risks? Which BG meters even report a value this high?

**Comment by marionbarker** [comment]
I confirmed this issue. 

I used the same SHA (which is the most recent dev version). 
The dev code is identical to the most recent alpha branch. (The SHA is different, but code is the same).

**Comment by MikePlante1** [comment]
I found the offending line in [DataTableRootView.swift](https://github.com/nightscout/Trio/blob/a364b62c7d1cd94397be1a3ad9e9e2e3e0971d48/FreeAPS/Sources/Modules/DataTable/View/DataTableRootView.swift#L157):

Looks like post https://github.com/nightscout/Trio/pull/140 : `0.8-14 mmol/L` and `40-720 mg/dL`
Pre-PR140 it was `2.2-21 mmol/L` & `40-380 mg/dL`

If we base it on the range of blood sugar meters, the popular Contour Next reads `20-600 mg/dL` & `0.6-33.3 mmol/L`. Strange that it can read significantly lower in mmol/L than mg/dL.

**Comment by marionbarker** [comment]
Are you going to do the PR or do you need me to do it?

**Comment by dsut4392** [comment]
Need to re-open this one, using dev bd56601, can now no longer enter a BG value over 9.0 mmol. As soon as you enter a “1” the entry goes to “1.0” and then the next digit is appende, e.g. try to enter 14.3 and you get 1.04 initially displayed which then reverts to 1.0. 

You can actually get he number you need entered by entering 9.9 and repeatedly hitting any number 5 or above, each tap increments the BG by 0.1.
