### ISSUE TITLE
Incorrect bolus amount entered due to data entry problem

### ISSUE THREAD

**Issue by marionbarker** [nightscout/Trio#358]
## Describe the bug
*I attempted to request a bolus of 1.05 U. I was not able to do that and discovered that 15U was entered instead.*

## Attach a Log
*No log is needed - this is a data field entry problem.*

## To Reproduce
*Steps to reproduce the behavior:*
1. *Go to manual bolus*
2. *you are in the BOLUS Amount Row automatically*
3. *Type these characters: 1, decimal-separator, 0, 5*
4. *As soon as you type the 0 after the decimal-separator, they both vanish leaving 1*
5. *After you type 5, you are left with an Amount of 15 U*

## Expected behavior
*This behavior of having `#.0` replaced with `#` (where I use "." as the decimal-separator) is seen in several entry fields.*

## Screenshots
![ui-error-bolus-entry](https://github.com/user-attachments/assets/be93f0d4-7e09-477e-b164-349d5e840650)

### Smartphone:
* Hardware: iPhone SE
* OS Version: iOS 17.5.1

### Pump:
* Manufacturer: DASH rPi simulator

### CGM:
* Device: NS as CGM

### Trio Version:
* Version Number: several
* Repo: *nightscout/trio*
* last test was with latest dev, commit 8303f0a8 with PR 352, 355 and 356 all applied

## Technical Details
*N/A*

## Additional context
Seems like this keeps cropping up - we need an overall fix here.
The mmol/L log glucose entry fix (PR 356) has the same behavior of modifying `#.0` to `#` during entry
This entry bug was independently verified.

**Comment by MikePlante1** [comment]
To clarify, this problematic behavior exists in current dev https://github.com/nightscout/Trio/commit/8303f0a881fab13690522ea02dba9944b6528f6e without any PRs applied, and none of the current PRs fix this problematic behavior.

**Comment by MikePlante1** [comment]
Looks like this issue started with this merge: https://github.com/nightscout/Trio/pull/337

**Comment by marionbarker** [comment]
After I noticed this last night, i did more tests today. 

I tested on straight dev. Then went back to when PR #337 was merged. Then back to straight dev. Then added all the open PRs cause that was my current config before opening this PR. 

This happened for all of those. 

When testing PR 337, I explicitly tested enact bolus screen along with many others. But I did not try this particular test.

**Comment by kskandis** [comment]
I might be wrong, but other data entry formatters seem to have issues, too.  For example, Meal Settings - Delay in Minutes/Max Duration in Hours/Interval in Minutes should be an Integer but data entry allows a decimal as shown in the image (taken with latest dev branch).  All 3 of these Meal Settings should be Integers, I believe (and they have `formatter.allowsFloats = false`), but they still allow decimal input.  Of course, the value does not get saved.  On returning back to Meal Settings, Delay shows the default value of 60.  Still, it might be confusing for users.  Also if I enter a number > 120, the number is accepted, but on returning back to Meal Settings, Delay shows 120.  I assume that is the max default value.

Should decimal input be allowed in these Meal Settings?

Also the Meal Settings for Max Carbs, Fat, Protein all have similar issues to the Bolus entry already documented but `maximumFractionDigits` is 3.

<img width="372" alt="image" src="https://github.com/user-attachments/assets/1ec5dba2-e0b8-4e26-ba6c-8e5191a5525b">
