### ISSUE TITLE
Rename "G6" -> "G6 / ONE" and "G7" -> "G7 / ONE+"

### ISSUE THREAD

**Issue by LiroyvH** [nightscout/Trio#379]
## Is your feature request related to a problem? Please describe.
Trio in the CGM selection only declares support for G6 and G7, whilst ONE and ONE+ also work with them (in that order) respectively.

## Describe the solution you'd like
Change CGM Selection / configuration options, menu's, etc. to read "Dexcom G6 / ONE" and "Dexcom G7 / ONE+" instead of "Dexcom G6" or "Dexcom G7" respectively. 

## Describe alternatives you've considered
Leave it as it is and let users figure it out themselves, just to f- with 'em. 

## Additional context
Primarily relevant in Settings -> CGM and its subsettings/submenus. (And localization strings)

## Technical Details
There are no additional dependencies other than the official Dexcom-apps of the respective sensor/transmitter.

## User Impact
Users will understand which option to choose if they wish to use ONE or ONE+, whereas they currently may believe they're unsupported or don't know what to select.

**Comment by Sjoerd-Bo3** [comment]
@LiroyvH I think #424 should fix this

**Comment by bjornoleh** [comment]
> @LiroyvH I think #424 should fix this

Confirmed!

<img src="https://github.com/user-attachments/assets/4b819a3d-edfd-4d9b-ae4e-2d1d850e88f1" width="300">
