### ISSUE TITLE
GH Build Action warns "Scheduled Sync and Build Disabled" with incorrect information

### ISSUE THREAD

**Issue by hummelstrand** [nightscout/Trio#387]
## Describe the bug
When building with action number 4, I get a warning that says "...please follow the instructions under the following path Trio/fastlane/testflight.md" but the path seems to be https://github.com/nightscout/Trio/blob/main/fastlane/testflight.md

## Expected behavior
If the warning is relevant, the path information should be updated, and possible hot linked.

## Screenshots
<img width="845" alt="image" src="https://github.com/user-attachments/assets/9f6c385a-a24e-4c8a-898b-b055ad3ac769">

### Trio Version:
* Version Number: * 0.2.0 main 6433d94 (https://github.com/hummelstrand/Trio/commit/6433d947ac6abffb4e381c32b59662314b65aa38)

* Repo: https://github.com/hummelstrand/Trio

**Comment by hummelstrand** [comment]
Edited to update with what seems to be the correct path to the markdown file.

**Comment by marionbarker** [comment]
Trio does have a fastlane folder and testflight.md is in the folder. My memory is that the error message is not a link, but instructions in how to navigate the user’s fork to find the file.

It is deliberate not to point to the docs because those links are subject to change. 

If it is a link, then it should be updated.

**Comment by hummelstrand** [comment]
@marionbarker The warning says "...under the following path `Trio/fastlane/testflight.md`" i.e. https://github.com/nightscout/Trio/fastlane/testflight.md which results in a 404, since the _actual_ path is `Trio/blob/main/fastlane/testflight.md` i.e. https://github.com/nightscout/Trio/blob/main/fastlane/testflight.md

**Comment by bjornoleh** [comment]
Sorry for being slightly off topic, but is this info correct? I thought scheduled sync and build was on by default for Trio and also Loop, and that disabling one or both are options? That’s how I read the testflight.md too.

**Comment by marionbarker** [comment]
If workflow is not enabled for GH_PAT, it is disabled.

**Comment by bjornoleh** [comment]
Ok, thanks. I would expect users to follow the instructions and enable the workflow scope, but this probably happens for users that skip that step passed on this:

```
Create GitHub Personal Access Token

If you have previously built another app using the "browser build" method, you use the same personal access token (GH_PAT), so skip this step.

```

**Comment by dnzxy** [comment]
It‘s the correct path in the repository folder structure, not the actual link path. 

If you look at the repository as a big project folder, you will have to go into root/fastlane/testflight.md. It’s not a path as in link-path.

![image](https://github.com/user-attachments/assets/bee3bedf-12d5-4309-a66d-aba0ed113e6c)

This is not really an issue/bug.
