### ISSUE TITLE
UI: ‘10.5’ mmol/L + ‘manual basal’ causes ‘10.5’ to wrap text

### ISSUE THREAD

**Issue by g5WS** [nightscout/Trio#390]
## Describe the bug
UI: ‘10.5’ mmol/L + ‘manual basal’ causes ‘10.5’ to wrap text

## Attach a Log
See image. 

## To Reproduce
Have not tried to reproduce. 

## Expected behavior
Major UI elements should fit on the screen without text wrapping

## Screenshots
Attached

### Smartphone:
* Hardware: iPhone 15 Plus
* OS Version: iOS 18.0

### Pump:
* Manufacturer: Insulet
* Model: Omnipod Eros

### CGM:
* Device: Dexcom G6
* Manager app: xDrip4iOS

### Trio Version:
* Version Number: 0.2.0 main
* Repo: *nightscout/trio*
* Git Reference: 
![IMG_1833](https://github.com/user-attachments/assets/8f0f7542-1b48-4d0a-996b-e1de8a75ad89)

**Comment by g5WS** [comment]
Oh, also, killing the app and opening it again didn’t solve the problem. 

It’s also happening with 10.4.

**Comment by Sjoerd-Bo3** [comment]
@g5WS Can you tell us what your text size settings in iOS is set too? It seems like you have larger / bolder text than usual.
This can impact the problem aswell.

**Comment by g5WS** [comment]
Here you go! While my font size is increased, it seems like there is enough real estate not to wrap the text. 

![IMG_1834](https://github.com/user-attachments/assets/d24c1be2-5ad7-4cd4-a22d-e5484db0fff0)

**Comment by Sjoerd-Bo3** [comment]
There are also defined safespaces, so it seems like there is enough. But it maybe needs to shrink in size to work.
