### ISSUE TITLE
Add Arabic Language to Crowdin

### ISSUE THREAD

**Issue by semophoto** [nightscout/Trio#394]
I would like to start contributing with Arabic translation please

## Is your feature request related to a problem? Please describe.

Not a problem, a Language feature request 

## Describe the solution you'd like

I would like the app to support the Arabic Language 
And support a right-to-left display "graph/chart" (long-term) 

## Describe alternatives you've considered

N/A

## Additional context

I've tried the Loop app Arabic translation, it was decent but missing a lot. 
Also iAPS has some translation done and i have been contributing there. 
Not sure if its possible to benefit all the apps with the same effort.

## Technical Details

The app functions in English while the phone is arabic. 
Some UI is inverted, however, the graph/chart is not.

## User Impact

I believe this among the docs would really benefit a large demographic of diabetics. 
I have been raising awareness in the community, it would be helpful to let people read and understand in their native language.

**Comment by bjornoleh** [comment]
Tagging @t1dude

**Comment by t1dude** [comment]
I have added Arabic to Crowdin and it is open for translation for anyone who signs up on https://crowdin.com/project/trio. We need to pay attention to new languages and make sure they behave as expected in the crowdin branch before we push to DEV.

**Comment by t1dude** [comment]
I'll close the issue for now, let's discuss the practicalities on Discord.
