### ISSUE TITLE
Rounding error in Log Glucose entry (and possibly elsewhere)

### ISSUE THREAD

**Issue by bjornoleh** [nightscout/Trio#396]
## Describe the bug
When entering BG values in the Log Glucose screen, there is rounding applied at the time of entering values. This gives the wrong result sometimes. Confirmed for when entering the value of 9,2 mmol/L, which is immediately registered as 9,1 mmol/L.

## To Reproduce
*Steps to reproduce the behavior:*
1. Set BG units to mmol/L
2. *Go to History / Glucose tab
3. *Click on `Log Glucose +`
4. *Enter `9,2`
5. *See the `New Glucose` value being entered as `9,1`

## Expected behavior
Duh :-)

### Trio Version:
* Version Number: *[e.g. 0.2.0]*
* Repo: *nightscout/trio*
* Git Reference: [6433d94](https://github.com/nightscout/Trio/commit/6433d947ac6abffb4e381c32b59662314b65aa38)

## Technical Details
*Built to phone, but should be easily reproducible in any setup

I'd expect there to be more instances of this rounding error, but did not look for them yet.

**Comment by dnzxy** [comment]
Fixed with #398 .
