### ISSUE TITLE
Discord URL

### ISSUE THREAD

**Issue by tonypartridge** [nightscout/Trio#410]
What's the new discord URL? The docs version has expired

**Comment by MikePlante1** [comment]
The link in `TrioDocs.org` seems to work fine for me. Could you please link the specific page that has the problem link?

Also, discord.diy-trio.org should redirect to the Trio Discord.

**Comment by tonypartridge** [comment]
Perfect thanks Mike, it was on the git read me and I'm sure somewhere else in the docs. I'll do a PR when I'm at a computer

**Comment by MikePlante1** [comment]
Ah, yes, I see now. [CODE_OF_CONDUCT.md](https://github.com/nightscout/Trio/blob/6433d947ac6abffb4e381c32b59662314b65aa38/CODE_OF_CONDUCT.md?plain=1#L62) and [README.md](https://github.com/nightscout/Trio/blob/6433d947ac6abffb4e381c32b59662314b65aa38/README.md?plain=1#L66)

Thanks for reporting it, I'll look out for the PR.

**Comment by dnzxy** [comment]
Solved with #412 . Thank you @tonypartridge .
