### ISSUE TITLE
AutosenseMax decimal issue

### ISSUE THREAD

**Issue by Danielsloop** [nightscout/Trio#415]
When changing AutosenseMax settings:

https://github.com/user-attachments/assets/3a64fb89-91a9-4403-8462-78c90431d2c3

 when I delete the fraction number/s the decimal comma disappears as well. This does not happen with AutosenseMin. This potentially can lead to setting an AutosenseMax of 12 instead of 1,2 if gone unnoticed. 

## Expected behavior
When I delete the fraction numbers that the decimal comma stays present as I have not deleted it.

## Screenshots
I've attached a video.

### Smartphone:
* Hardware: iPhone SE
* OS Version: *iOS 17.6.1

### Trio Version:
* Version Number: 0.2.0 Main 6433d94
* Repo: nightscout/trio

https://github.com/user-attachments/assets/a2042696-8a90-455a-8d7d-08ef21150d61

**Comment by dnzxy** [comment]
Will be addressed with 1.0.0 as it comes with entirely refactored settings.
