### ISSUE TITLE
COB - Incorrect after removing entries

### ISSUE THREAD

**Issue by tonypartridge** [nightscout/Trio#416]
If we go an remove duplicate entries, say for example you go to bolus for carbs and it warns bolus out of date and you go back and try again it duplicates the carbs and increases the COB onboard, so then you go into the carbs logs and remove the additional mistakes the COB doesn't update. Ideally we need to trigger an update similar to how we do when adding carbs.

**Comment by MikePlante1** [comment]
This is fixed in the upcoming v1.0, where COB and forecasts are updated as soon as a carb entry is deleted.

I presume COB updated for you within 5 minutes at the next loop cycle, though, at least?

**Comment by tonypartridge** [comment]
> This is fixed in the upcoming v1.0, where COB and forecasts are updated as soon as a carb entry is deleted.
> 
> I presume COB updated for you within 5 minutes at the next loop cycle, though, at least?

I didn't wait, I just entered a fake 0.1 fat to re-calculate.
