### ISSUE TITLE
"Add" button on basal profile screen disappears when an 11:30 pm basal segment is added

### ISSUE THREAD

**Issue by dsut4392** [nightscout/Trio#428]
## Describe the bug
*When you add a basal segment commencing at 11:30pm, the "Add" button disappears and you are unable to add any further basal segments, regardless of start time. Work-around: Deleting the 11:30pm segment (or editing the start time to an earlier time) re-enables the add button, allowing you to create new basal segment. *

## Attach a Log
*see video*

## To Reproduce
*Steps to reproduce the behaviour:*
1. *Go to 'Settings - Basal Profile'*
2. *Click on 'Add' to create a new basal segment, or edit an existing basal segment to start at 11:30pm*
3. *Scroll down to '....'*
4. *See error*

## Expected behaviour
*If there are basal start times that are unallocated (i.e. between 00:00 and 11:30pm, setting a basal segment start time at 11:30pm should not prevent you from creating earlier ones.\*

## Screenshots
*If applicable, add screenshots to help explain your problem.*

### Smartphone:
* Hardware: * iPhone 15 Pro Max]*
* OS Version: *iOS 17.7*

### Pump:
* Any - confirmed on Dash and Simulator

### Trio Version:
* Version Number: *0.2.1 main*
* Repo: *nightscout/trio*

**Comment by dsut4392** [comment]
https://github.com/user-attachments/assets/bddc4bf6-46ea-42c3-9add-7ad945ddf75f

**Comment by Sjoerd-Bo3** [comment]
Would be nice if the add button would appear in between possible segments right? So instead of an add button on the bottom, it will appear in between entries that are more than 0:30 apart?

Or an add button on top and a dialog before adding it to the list?

Or would this be awful? Just a first thought? Any other recommendations?

**Comment by dsut4392** [comment]
From this FB post: https://www.facebook.com/groups/diytrio/posts/1685489575518224

I don't think this really needs fixing in 0.2.1, the workaround is probably enough until 1.0 is released?

**Comment by Sjoerd-Bo3** [comment]
This is not ‘fixed’ in 1.0 either. It’s better, but your ‘issue’ is still not possible and needs the same work around.

**Comment by marionbarker** [comment]
Bump
