### ISSUE TITLE
Alternative optional insulin remaining display

### ISSUE THREAD

**Issue by bigolal007** [nightscout/Trio#436]
## Is your feature request related to a problem? Please describe.
Not related.

## Describe the solution you'd like
Having an optional display for the amount of insulin remaining for users on Omnipod Dash. 

My suggestion would be to have an option at some point for the user to input the amount of insulin they have entered into the pod - perhaps once the pod attachment is confirmed (final screen). In the settings,  you have the option to have either 50+U (default) displayed or the total amount of insulin e.g. 125U remaining.  The proposed display can calculated by the user entering the amount of insulin e.g. 200U and subtracting the Total Delivery figure (in pod details). Obviously this suggestion wouldn't be 100% accurate (maybe +/- 5U) until it reaches the 50U left report by Omnipod. **_Warning messages would need to be included describing the feature being optional and it's potential inaccuracy based upon the user's initial input._**

For me it'd be a great feature to help manage the amount of insulin I use so I can push the duration of my pod from two days out to the full three. In Australia, I'm limited to 13 boxes of pods for the year since I was approved, so at the moment I need to use pens for a month or two so as to not reach my limit approved by my private health insurance to paying the $200+ for each box.

## Describe alternatives you've considered
I haven't been able to come up with an alternative.

## Additional context
I have proposed this in the discord channel, and another use expressed that they would like this feature as well. I can't remember if a decision was made by any of the developers.

## Technical Details
I don't believe this would have any effect on the functionality of the app other than display. 

## User Impact
There's no issue at the moment. It would be a nice optional feature to have but certainly won't change my mind in using Trio.

**Comment by dnzxy** [comment]
> For me it'd be a great feature to help manage the amount of insulin I use so I can push the duration of my pod from two days out to the full three.

I‘m lost at this statement. You know how much you fill into the pod, you know your TDD / your insulin usage (of currently paired pod) respectively (can be checked via pod diagnostics) and you can then do X - Y. Unless you have wildly varying insulin needs between two pods, you should be able to note down that value a few pods on in a row and then use that number to fill
subsequent pods. Even easier than that would be to just do TDD x 3 + Y% (for wiggle room). 

It’s a bad idea to give users a false sense of information transparency based on guesstimated values, especially when it comes to insulin. FWIW, even the pod when displaying e.g. 45 U does not actually contain 45 U, but roughly +4 U of that.

**Comment by bigolal007** [comment]
That makes sense.

You're right - making a change that does impact a large group of users that
can have a significant impact isn't a good idea. I'll take what you have
said and use that method. It was a feature I've always wanted but haven't
considered the adverse effects for others.

Thanks for clarifying it for me.

**Comment by dnzxy** [comment]
The information you are seeking is already available at your fingertips. That’s why I am lost at your idea. All the data you need to save pods and know how much insulin to fill them with is available. Please be so kind as to explain it further instead of being defensive and throwing sarcasm at me. 

I’ll add some more background to my previous reply: Adding the factor of guesstimation and user input, when there can be a varying group of people filling and applying a pod for the actual T1 / Trio user, and a bunch of conditional logic on top of it, for a single pump option is a bad idea for safety concern and software design reasons, yes, in my opinion, as a developer.

**Comment by dnzxy** [comment]
On second thought, cause while your probably won’t believe me, I am throwing a bunch of things around in my head trying to look at your idea from various angles, this idea / request is probably pointed at the wrong party here. 

Let me explain why: 
We make use of the OmniBLE and OmniKit modules of the LoopKit framework. Those are our pump drivers. The entire pairing workflow / UI you go through is rooted in these modules. The information surrounding pod age, pod fill, the alerts you get for low reservoir or nearing expiry, all these things are rooted in these modules. They are propagated through various layers of the modules into actual Trio code and then processed for display on your phone through the UI. 

**_If_** this were ever a feature-set to be added, the place to do it would be during the pod priming and application workflow as an added layer/step (I hope it’s clear what I mean by that), so it’s an option that OmniBLE / OmniKit would need to provide us with. 

For that reason, I think this request is best pointed toward the maintainers of the submodules. If this were to be added there, we would (naturally, in keeping up with a homogenous iOS infrastructure for pump drivers) probably adopt it when we update our submodule dependencies. 

For the other reasons (see my previous 2 comments), I still don’t think this is a good idea, sorry. Trio does a great job (and the information readily available with the current pod UI) in giving you all the information you require. 

You can go into your pump settings in Trio, check the delivery of last pod, grab the precise (!) delivery info (precise to 0.05 U!) from there, compare it to your TDD of Trio, then calculate how much you should fill your new pod with. 

| Pod Settings | Last Pod Info |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/564254d3-7931-4390-b969-d3b563947ada) | ![image](https://github.com/user-attachments/assets/dfc3fd9b-d890-42e4-a31c-822560015fa1) |

**Comment by Sjoerd-Bo3** [comment]
I wholeheartedly agree with @dnzxy last post on this point. It doesn’t belong in Trio itself but the submodules. Although I think this is a guesstimating feature that shouldn't be done.

**Comment by bigolal007** [comment]
I must apologise. I wasn't being sarcastic and didnt mean for it to come
across that way at all.

I do appreciate your suggestion about the information at my fingertips -
perhaps my suggestion comes from a place of laziness and not wanting to do
the calculations. I didn't realise the amount of work it would take behind
the scenes, hence why I was thinking of it being a ‘small change’ if it
reads that way in my suggestion.

Given the amount of work involved as you've laid out and the risks the
feature creates, there would certainly be more risks than benefits. I think
time would  be better spent on other improvements/features.

I appreciate the work that you and everyone else involved have and are
continue to do on Trio. It's amazing and a big improvement on iAPS.

Once again, I do apologise for how my reply came across.

**Comment by Sjoerd-Bo3** [comment]
You are alright! It's not the amount of work that is the issue here. It's that the code that needs to change form this is in the modules, not Trio itself. But besides that, the guessing how much you much you injected into the pod is an issue. It's an inexact amount that the user needs to enter. But also can screw up, We cannot check that, or catch such a thing. So it's a false sense of security. Leading to more uncertainty than its doing good. I also wonder sometimes if I make it with the pod. But then I look at the amount delivered. and I know how much is in there from the begin. The amount remaining that the pod gives, is already the indication you seek, its also not that accurate, but to a certain amount (its always more imo). 

I believe this will lead to way more confusion then that it will solve.

**Comment by dsut4392** [comment]
@bigolal007 NDSS will have ways around the 13 box limit for pods, particularly if your insulin needs exceed 200U in 3 days. Contact them and explain your situation and there will be a batter solution than using pens for a month.

**Comment by bigolal007** [comment]
Really? I had no idea they'd be able to help - I thought it was only
through private health insurance. I'll have to give them a call tomorrow.

Thanks for the info!

**Comment by bigolal007** [comment]
Unfortunately got immediately dismissed after explaining my situation and
told to contact Omnipod. I have one box left, and the limit resets in March.

**Comment by Sjoerd-Bo3** [comment]
Could you guys maybe have the convo on discord or fb? Instead of the issue? Its not really meant for this, although I love that you guys are sharing info and such

**Comment by bigolal007** [comment]
Sure thing. Sorry.
