### ISSUE TITLE
Better warning for time being out of sync or being put out of sync by Trio

### ISSUE THREAD

**Issue by LiroyvH** [nightscout/Trio#441]
## Is your feature request related to a problem? Please describe.

When manually changing the time on a (Medtronic) pump, Trio will move it back to what it was without warning or notification. According to a link shared by Marion, regarding Loop (not Trio), this is desired behaviour. However, the implementation imho is not. 

## Describe the solution you'd like

Whilst the feature can make sense, the implementation imho needs improvement. Currently, the only thing you see is a yellow clock icon hidden away in pump settings which you'll generally never access for MDT after setup. I suggest showing a yellow clock icon on the home screen or otherwise give a notification that Trio modified the time of the pump. 

## Describe alternatives you've considered

None. Also, this behaviour and a note that users should not manually change the time on their pump should be documented. It currently isn't. 

## Additional context

- 

## Technical Details

-

## User Impact

Users will properly be warned about the pump time changing/being pushed out of sync (by design) by Trio. If not, the pump will be out of sync until the next DST. It may also save frustration not understanding why the pump keeps changing time for no apparent reason.

**Comment by marionbarker** [comment]
If the clock icon is not shown on the main screen for Trio 0.2.2 when there has been a time zone change, this issue should remain open until the next version is released. I know it is fixed there.

Alignment between phone time and pump time (with allowed time-zone differences) is a required feature of using a Medtronic pump. The reconciliation between pump reservoir history and app record for dosing from bolus or temporary bolus requires the time to be accurate.

In the olden days of Loop, there was a button for manually synching the time but as the code progressed, the time sync was modified to be automatic.

The only time difference allowed is when the phone is on a different time zone. In that case, all the therapy settings that have a schedule: Basal Rates, Carb Ratio, Insulin Sensitivity Factor and Target Glucose use the "pump time" for those schedules. The clock icon on the main screen following a time zone change, from travel or season, indicates that the "pump time" does not match the "phone time". When you update the "pump time" in that case, you are changing the hour.  Keeping the pump aligned to the minute/sec is automatic. This allows you the flexibility to decide when you want your settings to be modified. (For pod users - this is true across pods as well. Even though a pod doesn't have a date-time clock, the app keeps track of the time-zone for your pod and only changes it when you request the change.)

* https://loopkit.github.io/loopdocs/faqs/time-faqs/#time-zones-daylight-savings-time-summer-time
